version: "3.1"

services:
  db:
    image: ${POSTGRES_TAG}
    
    volumes:
      - PGDATA:/var/lib/postgresql/data
    networks:
      webnet:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1g
      restart_policy:
        condition: on-failure
  studio:
    image: studio:${IMAGE_TAG}    
    networks:
      webnet:
    environment:
      DATABASE_URL: ${DATABASE_URL}
    deploy:
      replicas: 1
      resources:
        limits:         
          memory: 250m
      restart_policy:
        condition: on-failure
  app:
    image: itahuduma:${IMAGE_TAG}    
    environment:
     # google credentials
       GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
       FIREBASE_API_KEY: ${FIREBASE_API_KEY}
       STORAGE_BUCKET: ${STORAGE_BUCKET}
       FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      #sendgrid email
       SENDGRID_API_KEY: ${SENDGRID_API_KEY}
       SENDGRID_SENDER_EMAIL: ${SENDGRID_SENDER_EMAIL}
       SENDGRID_ACCOUNT_ACTIVATION_TEMPLATE: ${SENDGRID_ACCOUNT_ACTIVATION_TEMPLATE}
       SENDGRID_ACCOUNT_DEACTIVATION_TEMPLATE: ${SENDGRID_ACCOUNT_DEACTIVATION_TEMPLATE}
       SENDGRID_WELCOME_TEMPLATE: ${SENDGRID_WELCOME_TEMPLATE}
       DATABASE_URL: ${DATABASE_URL}
      
    depends_on:
      - db
    volumes:
      - ${PWD}/console/${GOOGLE_APPLICATION_CREDENTIALS}:/usr/src/app/${GOOGLE_APPLICATION_CREDENTIALS}
      - ./webserver/web-root:/usr/src/app/dist/public
    networks:
      webnet:

    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "1"
      #     memory: 1g
      restart_policy:
        condition: on-failure
  
  redis:
    image: redis:alpine    
    networks:
      webnet:
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "1"
      #     memory: 1g
      restart_policy:
        condition: on-failure
  # graphhopper:
  #   image: graphhopper:${IMAGE_TAG}
  #   deploy:
  #     replicas: 1
  #     # resources:
  #     #   limits:
  #     #     cpus: "1"
  #     #     memory: 1g
  #     restart_policy:
  #       condition: on-failure
  #   volumes:
  #     - ./graphhopper/graph-cache:/usr/src/graph-cache
  #     # - ./graphhopper/config.yml:/usr/src/config.yml
  #   networks: 
  #     webnet:

  webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"
    volumes:
      - ./webserver/web-root:/var/www/html
      - ./webserver/nginx-conf:/etc/nginx/conf.d
      - ./webserver/certbot/certbot-etc:/etc/letsencrypt
      - ./webserver/certbot/certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    networks:
      webnet:
    deploy:
      replicas: 1
      # resources:
      #  limits:
      #    cpus: "1"
      #    memory: 1g
      restart_policy:
        condition: on-failure
        
networks:
  webnet:
volumes:
  PGDATA:

