version: "3.1"

services:
  db:
    image: ${POSTGRES_TAG}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - PGDATA:/var/lib/postgresql/data
    networks:
      webnet:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 1g
      restart_policy:
        condition: on-failure

  adminer:
    image: ${ADMINER_TAG}
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      webnet:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.05"
          memory: 128m
      restart_policy:
        condition: on-failure
  app:
    image: ${NODE_TAG}
    working_dir: /home/app
    command: yarn run start:docker:debug
    depends_on:
      - db
    ports:
      - ${APP_PORT}:3000
      - 9228:9229 #debugger port disable in production
    volumes:
      - ./:/home/app
    networks:
      webnet:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 1g
      restart_policy:
        condition: on-failure
networks:
  webnet:
volumes:
  PGDATA:
