import { v4 as uuid } from 'uuid';
export const BUSINESS_LOGIC_CONTAINER = uuid()

export const BUSINESS_LOGIC_HOOK = "BLoc_HOOK";

export const BUSINESS_LOGIC_VALIDATOR = "BLOC_VALIDATOR";//uuid()

export const PRISMA_LOGIC_HOOK="PRISMA_LOGIC_HOOK";

export const BUSINESS_LOGIC_FIELD = "BUSINESS_LOGIC_FIELD"

export const DATALOADER_ARGUMENT_KEY = "BUSINESS_LOGIC_DATALOADER_ARGUMENT_KEY"

export const DATALOADER_ARGUMENT_CONTEXT_KEY = "BUSINESS_LOGIC_DATALOADER_ARGUMENT_CONTEXT_KEY"