# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy files to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          passphrase: ${{secrets.PASSPHRASE }}
          key: ${{ secrets.SSHKEY }}
          source: "."
          target: "/home/${{ secrets.USERNAME }}/app"

      - name: BUILD SERVER        
        uses: appleboy/ssh-action@master
        env:
          PRISMA_ENV: ${{ secrets.PRISMA_ENV }}
          SERVER_ENV:  ${{ secrets.SERVER_ENV }}
          FIREBASE_ADM_AC: ${{ secrets.FIREBASE_ADM_AC }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSHKEY }}
          script: |
           cd /home/${{ secrets.USERNAME }}/app
           echo "$PRISMA_ENV" >> packages/console/prisma/.env
           echo "$SERVER_ENV" >> packages/console/.env
           mv packages/console/.env .env
           echo "$FIREBASE_ADM_AC" >> ${{ secrets.FIREBASE_ADM_FILE }}
           chmod +x stackdeploy
           ./stackdeploy
           rm -f stack.yml

